# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Christian Kirkham
email: cfkirkham@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Interaction UX Designer & Front-end Developer, crafting beautiful products that can be used fluidly on appropriate platforms.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ckirkham.com" # the base hostname & protocol for your site
twitter_username: chris_kirkham
github_username:  ckirkham

# Build settings
markdown: kramdown

collections:
    projects:
        output: true
        permalink: /projects/:path/